export enum AppTheme {
  LIGHT = 'light',
  DARK = 'dark',
}

export interface UserProfile {
  username: string;
  email: string;
  onboardingComplete: boolean;
  purposeAnalysis?: string; // Generated by AI
  purposeStatement?: string; // A short summary
}

export interface OnboardingAnswers {
  emotions: string;
  hobbies: string;
  importantValues: string;
  professionalGoals: string;
}

export interface JournalEntry {
  id: string;
  date: string; // ISO string
  timestamp: number;
  personal: string;
  family: string;
  professional: string;
  images: string[]; // Base64 strings
  sentiment?: string; // Specific emotion name (e.g., "Joy", "Gratitude")
  sentimentSummary?: string;
}

export interface AppSettings {
  theme: AppTheme;
  fontSize: 'small' | 'medium' | 'large';
}

export interface Message {
  role: 'user' | 'model';
  content: string;
  type?: 'text' | 'map_result' | 'search_result';
  metadata?: any;
}